[project]
name = "dphpc-fall25-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools>=75.0.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pygount>=3.1.0",
    "scipy>=1.16.3",
    "torch>=2.9.0",
    "jax>=0.8.0",
    "torchviz>=0.0.3",
]
